### ISSUE TITLE
Compiler error on using "typeof"

### ISSUE THREAD

**Issue by wisenomad** [steipete/PSTAlertController#17]
Xcode Version 6.1.1 (6A2008a)
iOS SDK 8.1
Default compiler (Apple LLVM 6.0)
C Language Dialect C99 (default option)

Even despite that compiler option "Allow 'asm', 'inline', 'typeof' " is enabled
but for some reason compiler doesn't like `typeof`

`__typeof` or `__typeof__` are recognized.

**Comment by steipete** [comment]
It's a gnu extension. You need to use the right compiler setting.

cheers,
Peter

**Comment by wisenomad** [comment]
Right.

But maybe it's better to use the most compatible option of `typeof` in the lib itself, so different ppl could use it with different project configurations?

**Comment by steipete** [comment]
GNU extensions are the default in Xcode.

cheers,
Peter
