### ISSUE TITLE
NSLayoutConstraint warning on iPad 

### ISSUE THREAD

**Issue by AlanAherne24** [steipete/PSTAlertController#18]
Running with iSO8 on an iPad with only one action field in the PSTAlertController results in a NsLayoutContraint warning.

translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7ffb8b4b8820 H:[UIView:0x7ffb88df6860(304)]>",
    "<NSLayoutConstraint:0x7ffb8b4f0a60 _UIAlertControllerView:0x7ffb8b4bb900.width == UIView:0x7ffb8b271520.width>",
    "<NSAutoresizingMaskLayoutConstraint:0x7ffb8b904050 h=--& v=--& H:[UIView:0x7ffb8b271520(298)]>",
    "<NSLayoutConstraint:0x7ffb8b47aa30 _UIAlertControllerView:0x7ffb8b4bb900.width >= UIView:0x7ffb88df6860.width>"
)

**Comment by steipete** [comment]
That's directly from UIAlertController, please report this to radar.apple.com instead.
