### ISSUE TITLE
Crash when view restricts orientation

### ISSUE THREAD

**Issue by billburgess** [steipete/PSTAlertController#21]
My startup views have orientation restricted on them. When I trigger the alert controller, it crashes with this error.

Supported orientations has no common orientation with the application, and [_UIAlertShimPresentingViewController shouldAutorotate] is returning YES

Has anyone else had this issue? It is happening on actual devices and the simulator. Running iOS 8.3.

**Comment by steipete** [comment]
Haven't tried that so far. It's just a shim on `UIAlertController` - how do things look when you use that directly?

**Comment by billburgess** [comment]
Oddly enough, nothing happens when I use `UIAlertController`. I try adding it to the view to the sender and nil for both, just stares at me.

I'm testing in my login controller. The view controller is displayed by adding to the window as the rootViewController by way of the AppDelegate. It's been this way for years, odd that it is behaving so badly now.

**Comment by billburgess** [comment]
I also checked against iOS 7.1 in the simulator to see if this was just a regression in iOS 8 or something, but same behavior there as well.

**Comment by billburgess** [comment]
Even regular `UIAlertView` is broken. Same weird error when it tries to present. I'm going to close this as I doubt it is related to your library. If you have any suggestions as to what I'm doing wrong, I'd love to hear them. I can enable rotation and everything works fine, just the initial couple of views where I restrict rotation is causing the problem.

**Comment by billburgess** [comment]
I'm pretty sure I just figured it out. It's embarrassing, but I'll mea culpa in case someone else stumbles across this. For my restricted orientation view, I was returning an invalid orientation mask in `supportedInterfaceOrientations`. `UIInterfaceOrientationPortrait != UIInterfaceOrientationMaskPortrait`

Sorry for the bother.
