### ISSUE TITLE
Assertion failure in -[PSTAlertController moveSheetToWeakStorage]

### ISSUE THREAD

**Issue by jbcaveman** [steipete/PSTAlertController#24]
Note that I am using this in a Swift project and building with Xcode 6.3.2, with deployment target set to iOS 7.1-8.3. This only happens when building for iOS 7.1 (or most likely any iOS < 8.0). After digging in, I found that PSTAlertController.m line 120 conditional is completely skipped ("#if __IPHONE_OS_VERSION_MIN_REQUIRED < 80000") so no _strongSheetStorage is created. Once I commented out line 120 and line 126, the app functioned correctly when building for iOS 7.1.

**Comment by jbcaveman** [comment]
Not sure of the effects of this on the rest of the code, so I am posting this issue for someone more knowledgeable than me to address.

**Comment by steipete** [comment]
What reason would there be to skip that? We use the same with that configuration and it works fine. Are you using pods or any other non-default configuration?

**Comment by jbcaveman** [comment]
Yes. Looks like only MBProgressHUD and TMCache (dependency) are using that same #if clause and it's working fine. Full list:
pod 'Bolts'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'SlackTextViewController'
pod 'MBProgressHUD'
pod 'REFormattedNumberField'
pod 'AWSCore'
pod 'AWSS3'
pod 'PixateFreestyle'
pod 'NSDate-Time-Ago'
pod 'GoogleAnalytics-iOS-SDK'
pod 'PSTAlertController'

**Comment by steipete** [comment]
Try integrating it directly to see if it makes a difference.

**Comment by jbcaveman** [comment]
How do you mean?

**Comment by steipete** [comment]
Try StackOverflow to see how to integrate source files without cocoapods. 

I'm closing this as we use the framework in the same way and I'm 100% sure it's just some issue with either our pod or your Xcode configuration.

**Comment by jbcaveman** [comment]
Ah yes, I see what you are suggesting. I'll give that a try when I have some time and report back as FYI.

**Comment by neil-wu** [comment]
I met the same error as jbcaveman.  (my deployment target is also set to 7.1, with xcode 6.4)
integrate source files without cocoapods also have this error.
