### ISSUE TITLE
Add Nullability annotations

### ISSUE THREAD

**Issue by bjtitus** [steipete/PSTAlertController#25]
Add nullability annotations for use with Swift:

https://developer.apple.com/swift/blog/?id=25

Using this API would be much nicer with proper nullability annotations. I was hoping to get feedback on whether this is worth doing. The syntax changed between Xcode 6 & 7 so there will be some compatibility issues there. Maybe best to wait for 7 to release.

**Comment by steipete** [comment]
I'm not sure this project is useful once Xcode 7 is out. It was meant as a bridge until you can drop iOS 7; which by the time Xcode 7 is out most people will have done.

**Comment by accatyyc** [comment]
Don't agree @steipete. We will support iOS7 for a foreseeable future at least. We don't use Swift, but there are some other issues. Might submit some PR's for those.

**Comment by steipete** [comment]
Sure thing. I'll review and merge a nullability PR or other related fixes; just saying that I won't find the time to do this on my own since I'm happy to no longer having to use this :)
