### ISSUE TITLE
Release new version of this

### ISSUE THREAD

**Issue by accatyyc** [steipete/PSTAlertController#28]
I think it's time for a new CocoaPods release since it now has nullability for Swift, and the Xcode7 warnings and some additional bugs have been fixed.

**Comment by imaks** [comment]
+1

**Comment by macecchi** [comment]
+1

**Comment by accatyyc** [comment]
Because of lack of responses I have decided to maintain a fork of this. If you want to use the latest version (1.1.1), you can add this to your Podfile:

`pod 'PSTAlertController', :git => 'https://github.com/accatyyc/PSTAlertController.git'`

You are welcome to send any pull requests to that repo!

**Comment by steipete** [comment]
Thanks for the effort - would have been nicer to get a heads up before forking. It was on my list.

Just pushed Cocoapods spec to 1.2 and updated the readme to reflect the changes.

**Comment by accatyyc** [comment]
:+1: thanks. Then the fork will not need to be maintained. No big matter, it was just for custom Podfile configs.
