### ISSUE TITLE
Got compile error with   NSArray<PSTAlertAction *> 

### ISSUE THREAD

**Issue by narychen** [steipete/PSTAlertController#32]
I installed through pod install
when compiled in xcode it appeared error on line 71
@property (nullable, nonatomic, copy, readonly) NSArray<PSTAlertAction *> *actions;
and line 75
@property (nullable, nonatomic, readonly) NSArray<UITextField *> *textFields;
parse issue property requires fields to be named
seems like the syntax is wrong

what does the asterisk mean in the protocol field? I've never seen it before

**Comment by narychen** [comment]
I just read it's an ios 9 objective generics syntax. Maybe I should try updating my xcode and do it again.

**Comment by steipete** [comment]
Yes we bumped to Xcode 7 required.
